name: fulfill_service_request
publish_to: none


environment:
  sdk: '>=3.5.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^9.0.0
  component_library:
    path: ../../component_library
  function_and_extension_library:
    path: ../../function_and_extension_library
  domain_models:
    path: ../../domain_models
  form_fields:
    path: ../../form_fields

  service_repository:
    path: ../../service_repository
  user_repository:
    path: ../../user_repository
  dispute_repository:
    path: ../../dispute_repository

  google_maps_flutter: ^2.9.0
  intl: any
  location: ^7.0.1
  image_picker: ^1.1.2
dev_dependencies:
  flutter_lints: ^4.0.0
