name: tymer

publish_to: 'none'
version: 1.0.3+7
environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  routemaster: ^1.0.1
  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  flutter_lints: ^3.0.1
  dio: ^5.8.0+1


  # Local Packages
  tymer_api:
    path: packages/tymer_api
  key_value_storage:
    path: packages/key_value_storage
  user_repository:
    path: packages/user_repository
  wallet_repository:
    path: packages/wallet_repository
  service_repository:
    path: packages/service_repository
  dispute_repository:
    path: packages/dispute_repository
  support_repository:
    path: packages/support_repository
  paymob_api:
    path: packages/paymob_api
  paymob_repository:
    path: packages/paymob_repository
  function_and_extension_library:
    path: packages/function_and_extension_library
  notifications_service:
    path: packages/notifications_service
  monitoring:
    path: packages/monitoring





  initial:
    path: packages/features/initial
  tab_container:
    path: packages/features/tab_container
  home:
    path: packages/features/home
  support_chat:
    path: packages/features/support_chat
  disputes:
    path: packages/features/disputes
  confirm_dispute:
    path: packages/features/confirm_dispute
  choose_service:
    path: packages/features/choose_service
  request_service:
    path: packages/features/request_service
  service_request_status:
    path: packages/features/service_request_status
  provide_service:
    path: packages/features/provide_service
  accept_service_request:
    path: packages/features/accept_service_request
  fulfill_service_request:
    path: packages/features/fulfill_service_request
  dispute_chat:
    path: packages/features/dispute_chat
  order_history:
    path: packages/features/order_history
  wallet:
    path: packages/features/wallet
  payment_history:
    path: packages/features/payment_history
  top_up_information:
    path: packages/features/top_up_information
  top_up_confirmation:
    path: packages/features/top_up_confirmation
  choose_top_up_method:
    path: packages/features/choose_top_up_method
  choose_withdraw_method:
    path: packages/features/choose_withdraw_method
  withdraw:
    path: packages/features/withdraw
  profile:
    path: packages/features/profile
  change_language:
    path: packages/features/change_language
  delete_account:
    path: packages/features/delete_account
  online_payment:
    path: packages/features/online_payment


  # Authentication
  sign_in:
    path: packages/features/sign_in
  sign_up:
    path: packages/features/sign_up
  verify_otp:
    path: packages/features/verify_otp
  forgot_password:
    path: packages/features/forgot_password
  change_password:
    path: packages/features/change_password
  change_phone:
    path: packages/features/change_phone




  # Domain Models and Component Library
  domain_models:
    path: packages/domain_models
  component_library:
    path: packages/component_library




dependency_overrides:
  google_maps_flutter_ios: 2.13.1

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal/Tajawal-Black.ttf
        - asset: fonts/Tajawal/Tajawal-Bold.ttf
        - asset: fonts/Tajawal/Tajawal-ExtraBold.ttf
        - asset: fonts/Tajawal/Tajawal-ExtraLight.ttf
        - asset: fonts/Tajawal/Tajawal-Light.ttf
        - asset: fonts/Tajawal/Tajawal-Medium.ttf
        - asset: fonts/Tajawal/Tajawal-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Black.ttf
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat/Montserrat-Light.ttf
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf

  assets:
    - assets/
    - assets/icons/
    - assets/icons/tab_container/

# Add under features section
