name: sign_in
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter_bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  function_and_extension_library:
    path: ../../function_and_extension_library
  component_library:
    path: ../../component_library
  user_repository:
    path: ../../user_repository
  service_repository:
    path: ../../service_repository
  form_fields:
    path: ../../form_fields
  domain_models:
    path: ../../domain_models
  intl: any
  equatable: ^2.0.5
  rxdart: ^0.27.7
dev_dependencies:
  flutter_lints: ^4.0.0
