// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8cTb-Dzo0l2-WqUSQnoUneHAX-y_K-A4',
    appId: '1:632819012871:android:f6296969e170a9d25661a2',
    messagingSenderId: '632819012871',
    projectId: 'tymer-app',
    storageBucket: 'tymer-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuVUkArhvSaJTPMd9HMdTo70HhbsqkERs',
    appId: '1:632819012871:ios:9776c8e1c16f140e5661a2',
    messagingSenderId: '632819012871',
    projectId: 'tymer-app',
    storageBucket: 'tymer-app.firebasestorage.app',
    iosBundleId: 'com.tymer',
  );


}

