arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: change_language_localizations.dart
output-class: ChangeLanguageLocalizations
synthetic-package: false
nullable-getter: false