arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: choose_top_up_method_localizations.dart
output-class: ChooseTopUpMethodLocalizations
synthetic-package: false
nullable-getter: false