arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: online_payment_localizations.dart
output-class: OnlinePaymentLocalizations
synthetic-package: false
nullable-getter: false
