name: top_up_confirmation
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^9.0.0
  form_fields:
    path: ../../form_fields
  component_library:
    path: ../../component_library
  domain_models:
    path: ../../domain_models
  function_and_extension_library:
    path: ../../function_and_extension_library
  user_repository:
    path: ../../user_repository
  wallet_repository:
    path: ../../wallet_repository
  image_picker: ^1.1.2
  webview_flutter: ^4.10.0
dev_dependencies:
  flutter_lints: ^4.0.0 