name: service_repository
publish_to: none

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  tymer_api:
    path: ../tymer_api
  key_value_storage:
    path: ../key_value_storage
  domain_models:

    path: ../domain_models
  function_and_extension_library:
    path: ../function_and_extension_library
  rxdart: ^0.27.1
  equatable: ^2.0.5
  google_maps_flutter: ^2.9.0
  url_launcher: ^6.3.1
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
dev_dependencies:
  flutter_lints: ^4.0.0
