arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: request_service_localizations.dart
output-class: RequestServiceLocalizations
synthetic-package: false
nullable-getter: false